severity: warning

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true
    max-elements: 1

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  DuplicateProperty:
   enabled: false

  PseudoElement:
    enabled: false

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: ^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes

  VendorPrefix:
    enabled: false
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ColorVariable:
    enabled: false

  TrailingWhitespace:
    enabled: false

  NestingDepth:
    enabled: false
    max_depth: 4
    ignore_parent_selectors: false

  SelectorDepth:
    enabled: false
    max_depth: 4

  FinalNewline:
    enabled: false
    present: true